In [22]:
import pandas as pd

In [23]:
dataset=pd.read_csv('heart.csv')

In [24]:
dataset

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [25]:
dataset.columns

Index(['age', 'sex', 'cp', 'trtbps', 'chol', 'fbs', 'restecg', 'thalachh',
       'exng', 'oldpeak', 'slp', 'caa', 'thall', 'output'],
      dtype='object')

In [26]:
y=dataset['output']

In [27]:
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: output, Length: 303, dtype: int64

In [28]:
x=dataset[['age', 'sex', 'cp', 'trtbps', 'chol', 'fbs', 'restecg', 'thalachh',
       'exng', 'oldpeak', 'slp', 'caa', 'thall']]

In [29]:
x

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2

In [30]:

from sklearn.model_selection import train_test_split

In [32]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

In [33]:
x_train.shape

(242, 13)

In [34]:
x_train

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall
132,42,1,1,120,295,0,1,162,0,0.0,2,0,2
202,58,1,0,150,270,0,0,111,1,0.8,2,0,3
196,46,1,2,150,231,0,1,147,0,3.6,1,0,2
75,55,0,1,135,250,0,0,161,0,1.4,1,0,2
176,60,1,0,117,230,1,1,160,1,1.4,2,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
188,50,1,2,140,233,0,1,163,0,0.6,1,1,3
71,51,1,2,94,227,0,1,154,1,0.0,2,1,3
106,69,1,3,160,234,1,0,131,0,0.1,1,1,2
270,46,1,0,120,249,0,0,144,0,0.8,2,0,3
102,63,0,1,140,195,0,1,179,0,0.0,2,2,2

In [35]:
y_train.shape

(242,)

In [36]:
from keras.models import Sequential

In [37]:
from keras.layers import Dense

In [38]:
from keras.optimizers import Adam

In [39]:
model=Sequential()

In [40]:
model.add(Dense(input_dim=13,units=12,activation='relu'))

In [41]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_3 (Dense)              (None, 12)                168
=================================================================
Total params: 168
Trainable params: 168
Non-trainable params: 0
_________________________________________________________________

In [42]:
model.add(Dense(units=8,activation='relu'))

In [43]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_3 (Dense)              (None, 12)                168
_________________________________________________________________
dense_4 (Dense)              (None, 8)                 104
=================================================================
Total params: 272
Trainable params: 272
Non-trainable params: 0
_________________________________________________________________

In [44]:

model.add(Dense(units=1,activation='sigmoid'))

In [45]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_3 (Dense)              (None, 12)                168
_________________________________________________________________
dense_4 (Dense)              (None, 8)                 104
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 9
=================================================================
Total params: 281
Trainable params: 281
Non-trainable params: 0
_________________________________________________________________

In [46]:
model.compile(loss='binary_crossentropy',optimizer=Adam(learning_rate=0.001),metrics=['accuracy'])

In [47]:
model.fit(x_train,y_train,epochs=200)

Epoch 1/200
8/8 [==============================] - 0s 8ms/step - loss: 11.7438 - accuracy: 0.5496
Epoch 2/200
8/8 [==============================] - 0s 2ms/step - loss: 4.7145 - accuracy: 0.5579
Epoch 3/200
8/8 [==============================] - 0s 1ms/step - loss: 2.4515 - accuracy: 0.4545
Epoch 4/200
8/8 [==============================] - 0s 2ms/step - loss: 2.0789 - accuracy: 0.5041
Epoch 5/200
8/8 [==============================] - 0s 1ms/step - loss: 1.4513 - accuracy: 0.6033
Epoch 6/200
8/8 [==============================] - 0s 2ms/step - loss: 1.3482 - accuracy: 0.6240
Epoch 7/200
8/8 [==============================] - 0s 1ms/step - loss: 1.0488 - accuracy: 0.6074
Epoch 8/200
8/8 [==============================] - 0s 1ms/step - loss: 0.9743 - accuracy: 0.6488
Epoch 9/200
8/8 [==============================] - 0s 2ms/step - loss: 0.9086 - accuracy: 0.6736
Epoch 10/200
8/8 [==============================] - 0s 1ms/step - loss: 0.8456 - accuracy: 0.6694
Epoch 11/200
8/8 [==============================] - 0s 1ms/step - loss: 0.8162 - accuracy: 0.6612
Epoch 12/200
8/8 [==============================] - 0s 2ms/step - loss: 0.7755 - accuracy: 0.6736
Epoch 13/200
8/8 [==============================] - 0s 2ms/step - loss: 0.7479 - accuracy: 0.6612
Epoch 14/200
8/8 [==============================] - 0s 1ms/step - loss: 0.7358 - accuracy: 0.6570
Epoch 15/200
8/8 [==============================] - 0s 1ms/step - loss: 0.6794 - accuracy: 0.6736
Epoch 16/200
8/8 [==============================] - 0s 1ms/step - loss: 0.6809 - accuracy: 0.6570
Epoch 17/200
8/8 [==============================] - 0s 2ms/step - loss: 0.6552 - accuracy: 0.6529
Epoch 18/200
8/8 [==============================] - 0s 1ms/step - loss: 0.6314 - accuracy: 0.6694
Epoch 19/200
8/8 [==============================] - 0s 2ms/step - loss: 0.6216 - accuracy: 0.6570
Epoch 20/200
8/8 [==============================] - 0s 2ms/step - loss: 0.5974 - accuracy: 0.6653
Epoch 21/200
8/8 [==============================] - 0s 2ms/step - loss: 0.5999 - accuracy: 0.6818
Epoch 22/200
8/8 [==============================] - 0s 1ms/step - loss: 0.5805 - accuracy: 0.6694
Epoch 23/200
8/8 [==============================] - 0s 1ms/step - loss: 0.5848 - accuracy: 0.6860
Epoch 24/200
8/8 [==============================] - 0s 1ms/step - loss: 0.5847 - accuracy: 0.6653
Epoch 25/200
8/8 [==============================] - 0s 1ms/step - loss: 0.5654 - accuracy: 0.6983
Epoch 26/200
8/8 [==============================] - 0s 2ms/step - loss: 0.5627 - accuracy: 0.6983
Epoch 27/200
8/8 [==============================] - 0s 1ms/step - loss: 0.5790 - accuracy: 0.6860
Epoch 28/200
8/8 [==============================] - 0s 1ms/step - loss: 0.5762 - accuracy: 0.6818
Epoch 29/200
8/8 [==============================] - 0s 1ms/step - loss: 0.5582 - accuracy: 0.6777
Epoch 30/200
8/8 [==============================] - 0s 1ms/step - loss: 0.5451 - accuracy: 0.7025
Epoch 31/200
8/8 [==============================] - 0s 2ms/step - loss: 0.5414 - accuracy: 0.7107
Epoch 32/200
8/8 [==============================] - 0s 1ms/step - loss: 0.5338 - accuracy: 0.7231
Epoch 33/200
8/8 [==============================] - 0s 1ms/step - loss: 0.5351 - accuracy: 0.7107
Epoch 34/200
8/8 [==============================] - 0s 2ms/step - loss: 0.5500 - accuracy: 0.7107
Epoch 35/200
8/8 [==============================] - 0s 1ms/step - loss: 0.5335 - accuracy: 0.7107
Epoch 36/200
8/8 [==============================] - 0s 2ms/step - loss: 0.5241 - accuracy: 0.7231
Epoch 37/200
8/8 [==============================] - 0s 1ms/step - loss: 0.5329 - accuracy: 0.7025
Epoch 38/200
8/8 [==============================] - 0s 1ms/step - loss: 0.5419 - accuracy: 0.7025
Epoch 39/200
8/8 [==============================] - 0s 1ms/step - loss: 0.5183 - accuracy: 0.7521
Epoch 40/200
8/8 [==============================] - 0s 1ms/step - loss: 0.5179 - accuracy: 0.7314
Epoch 41/200
8/8 [==============================] - 0s 1ms/step - loss: 0.5126 - accuracy: 0.7231
Epoch 42/200
8/8 [==============================] - 0s 2ms/step - loss: 0.5176 - accuracy: 0.7397
Epoch 43/200
8/8 [==============================] - 0s 1ms/step - loss: 0.5306 - accuracy: 0.7397
Epoch 44/200
8/8 [==============================] - 0s 1ms/step - loss: 0.5287 - accuracy: 0.7397
Epoch 45/200
8/8 [==============================] - 0s 3ms/step - loss: 0.5147 - accuracy: 0.7397
Epoch 46/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4998 - accuracy: 0.7686
Epoch 47/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4907 - accuracy: 0.7686
Epoch 48/200
8/8 [==============================] - 0s 1ms/step - loss: 0.5002 - accuracy: 0.7521
Epoch 49/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4883 - accuracy: 0.7479
Epoch 50/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4960 - accuracy: 0.7727
Epoch 51/200
8/8 [==============================] - 0s 1ms/step - loss: 0.5136 - accuracy: 0.7314
Epoch 52/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4885 - accuracy: 0.7686
Epoch 53/200
8/8 [==============================] - 0s 2ms/step - loss: 0.4826 - accuracy: 0.7769
Epoch 54/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4851 - accuracy: 0.7645
Epoch 55/200
8/8 [==============================] - 0s 1ms/step - loss: 0.5053 - accuracy: 0.7397
Epoch 56/200
8/8 [==============================] - 0s 2ms/step - loss: 0.4785 - accuracy: 0.7686
Epoch 57/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4959 - accuracy: 0.7603
Epoch 58/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4935 - accuracy: 0.7438
Epoch 59/200
8/8 [==============================] - 0s 2ms/step - loss: 0.4726 - accuracy: 0.7727
Epoch 60/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4659 - accuracy: 0.7603
Epoch 61/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4774 - accuracy: 0.7562
Epoch 62/200
8/8 [==============================] - 0s 3ms/step - loss: 0.4620 - accuracy: 0.7727
Epoch 63/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4601 - accuracy: 0.7893
Epoch 64/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4718 - accuracy: 0.7686
Epoch 65/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4917 - accuracy: 0.7521
Epoch 66/200
8/8 [==============================] - 0s 2ms/step - loss: 0.4947 - accuracy: 0.7645
Epoch 67/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4785 - accuracy: 0.7727
Epoch 68/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4592 - accuracy: 0.7769
Epoch 69/200
8/8 [==============================] - 0s 1ms/step - loss: 0.5073 - accuracy: 0.7479
Epoch 70/200
8/8 [==============================] - 0s 2ms/step - loss: 0.4632 - accuracy: 0.7893
Epoch 71/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4590 - accuracy: 0.7727
Epoch 72/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4470 - accuracy: 0.7810
Epoch 73/200
8/8 [==============================] - 0s 2ms/step - loss: 0.4477 - accuracy: 0.7810
Epoch 74/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4454 - accuracy: 0.7934
Epoch 75/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4465 - accuracy: 0.7893
Epoch 76/200
8/8 [==============================] - 0s 2ms/step - loss: 0.4365 - accuracy: 0.8223
Epoch 77/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4627 - accuracy: 0.7769
Epoch 78/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4942 - accuracy: 0.7397
Epoch 79/200
8/8 [==============================] - 0s 4ms/step - loss: 0.4643 - accuracy: 0.7810
Epoch 80/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4812 - accuracy: 0.7521
Epoch 81/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4861 - accuracy: 0.7479
Epoch 82/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4836 - accuracy: 0.7521
Epoch 83/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4447 - accuracy: 0.8140
Epoch 84/200

8/8 [==============================] - 0s 2ms/step - loss: 0.4287 - accuracy: 0.8140
Epoch 85/200
8/8 [==============================] - 0s 2ms/step - loss: 0.4592 - accuracy: 0.7893
Epoch 86/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4289 - accuracy: 0.8017
Epoch 87/200
8/8 [==============================] - 0s 2ms/step - loss: 0.4376 - accuracy: 0.7975
Epoch 88/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4392 - accuracy: 0.7769
Epoch 89/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4502 - accuracy: 0.7769
Epoch 90/200
8/8 [==============================] - 0s 3ms/step - loss: 0.4925 - accuracy: 0.7686
Epoch 91/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4423 - accuracy: 0.8140
Epoch 92/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4400 - accuracy: 0.7975
Epoch 93/200
8/8 [==============================] - 0s 3ms/step - loss: 0.4301 - accuracy: 0.7975
Epoch 94/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4429 - accuracy: 0.7893
Epoch 95/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4302 - accuracy: 0.8058
Epoch 96/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4266 - accuracy: 0.8347
Epoch 97/200
8/8 [==============================] - ETA: 0s - loss: 0.5150 - accuracy: 0.71 - 0s 1ms/step - loss: 0.4321 - accuracy: 0.8017
Epoch 98/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4233 - accuracy: 0.8099
Epoch 99/200
8/8 [==============================] - 0s 2ms/step - loss: 0.4604 - accuracy: 0.7769
Epoch 100/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4385 - accuracy: 0.8017
Epoch 101/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4347 - accuracy: 0.7893
Epoch 102/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4193 - accuracy: 0.8058
Epoch 103/200
8/8 [==============================] - 0s 2ms/step - loss: 0.4370 - accuracy: 0.8017
Epoch 104/200
8/8 [==============================] - 0s 2ms/step - loss: 0.4020 - accuracy: 0.8388
Epoch 105/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4273 - accuracy: 0.7934
Epoch 106/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4228 - accuracy: 0.8140
Epoch 107/200
8/8 [==============================] - 0s 3ms/step - loss: 0.4084 - accuracy: 0.8264
Epoch 108/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4079 - accuracy: 0.8223
Epoch 109/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4234 - accuracy: 0.8017
Epoch 110/200
8/8 [==============================] - 0s 5ms/step - loss: 0.4345 - accuracy: 0.8099
Epoch 111/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4359 - accuracy: 0.8017
Epoch 112/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4157 - accuracy: 0.8182
Epoch 113/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4105 - accuracy: 0.8182
Epoch 114/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4050 - accuracy: 0.8140
Epoch 115/200
8/8 [==============================] - 0s 3ms/step - loss: 0.3988 - accuracy: 0.8388
Epoch 116/200
8/8 [==============================] - 0s 2ms/step - loss: 0.3998 - accuracy: 0.8223
Epoch 117/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4564 - accuracy: 0.7893
Epoch 118/200
8/8 [==============================] - 0s 2ms/step - loss: 0.4367 - accuracy: 0.7934
Epoch 119/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4326 - accuracy: 0.7934
Epoch 120/200
8/8 [==============================] - 0s 2ms/step - loss: 0.4397 - accuracy: 0.8017
Epoch 121/200
8/8 [==============================] - 0s 2ms/step - loss: 0.4031 - accuracy: 0.8306
Epoch 122/200
8/8 [==============================] - ETA: 0s - loss: 0.3459 - accuracy: 0.84 - 0s 2ms/step - loss: 0.4129 - accuracy: 0.8306
Epoch 123/200
8/8 [==============================] - ETA: 0s - loss: 0.3343 - accuracy: 0.87 - 0s 2ms/step - loss: 0.4146 - accuracy: 0.8017
Epoch 124/200
8/8 [==============================] - 0s 2ms/step - loss: 0.4219 - accuracy: 0.7975
Epoch 125/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4144 - accuracy: 0.7975
Epoch 126/200
8/8 [==============================] - 0s 5ms/step - loss: 0.4069 - accuracy: 0.8017
Epoch 127/200
8/8 [==============================] - 0s 2ms/step - loss: 0.4048 - accuracy: 0.7893
Epoch 128/200
8/8 [==============================] - 0s 4ms/step - loss: 0.4073 - accuracy: 0.8306
Epoch 129/200
8/8 [==============================] - 0s 2ms/step - loss: 0.3995 - accuracy: 0.8140
Epoch 130/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4154 - accuracy: 0.7975
Epoch 131/200
8/8 [==============================] - 0s 2ms/step - loss: 0.4027 - accuracy: 0.8058
Epoch 132/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4257 - accuracy: 0.8017
Epoch 133/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4090 - accuracy: 0.8140
Epoch 134/200
8/8 [==============================] - 0s 1ms/step - loss: 0.3949 - accuracy: 0.8223
Epoch 135/200
8/8 [==============================] - 0s 2ms/step - loss: 0.3934 - accuracy: 0.8471
Epoch 136/200
8/8 [==============================] - 0s 3ms/step - loss: 0.3977 - accuracy: 0.8347
Epoch 137/200
8/8 [==============================] - 0s 1ms/step - loss: 0.3932 - accuracy: 0.8182
Epoch 138/200
8/8 [==============================] - 0s 1ms/step - loss: 0.3901 - accuracy: 0.8347
Epoch 139/200
8/8 [==============================] - 0s 2ms/step - loss: 0.4009 - accuracy: 0.8058
Epoch 140/200
8/8 [==============================] - 0s 2ms/step - loss: 0.3855 - accuracy: 0.8430
Epoch 141/200
8/8 [==============================] - 0s 2ms/step - loss: 0.4339 - accuracy: 0.7893
Epoch 142/200
8/8 [==============================] - 0s 2ms/step - loss: 0.4001 - accuracy: 0.7934
Epoch 143/200
8/8 [==============================] - 0s 1ms/step - loss: 0.3940 - accuracy: 0.8306
Epoch 144/200
8/8 [==============================] - 0s 1ms/step - loss: 0.3987 - accuracy: 0.8182
Epoch 145/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4128 - accuracy: 0.8058
Epoch 146/200
8/8 [==============================] - 0s 2ms/step - loss: 0.4016 - accuracy: 0.8388
Epoch 147/200
8/8 [==============================] - 0s 3ms/step - loss: 0.3840 - accuracy: 0.8388
Epoch 148/200
8/8 [==============================] - 0s 1ms/step - loss: 0.3804 - accuracy: 0.8430
Epoch 149/200
8/8 [==============================] - 0s 2ms/step - loss: 0.3856 - accuracy: 0.8306
Epoch 150/200
8/8 [==============================] - 0s 1ms/step - loss: 0.3985 - accuracy: 0.8017
Epoch 151/200
8/8 [==============================] - 0s 2ms/step - loss: 0.3993 - accuracy: 0.8017
Epoch 152/200
8/8 [==============================] - 0s 2ms/step - loss: 0.3836 - accuracy: 0.8264
Epoch 153/200
8/8 [==============================] - 0s 2ms/step - loss: 0.3957 - accuracy: 0.8306
Epoch 154/200
8/8 [==============================] - 0s 2ms/step - loss: 0.3874 - accuracy: 0.7975
Epoch 155/200
8/8 [==============================] - 0s 6ms/step - loss: 0.3889 - accuracy: 0.8512
Epoch 156/200
8/8 [==============================] - 0s 2ms/step - loss: 0.3764 - accuracy: 0.8512
Epoch 157/200
8/8 [==============================] - 0s 1ms/step - loss: 0.3816 - accuracy: 0.8471
Epoch 158/200
8/8 [==============================] - 0s 4ms/step - loss: 0.3767 - accuracy: 0.8347
Epoch 159/200
8/8 [==============================] - 0s 2ms/step - loss: 0.3793 - accuracy: 0.8347
Epoch 160/200
8/8 [==============================] - 0s 2ms/step - loss: 0.3836 - accuracy: 0.8306
Epoch 161/200
8/8 [==============================] - 0s 2ms/step - loss: 0.3876 - accuracy: 0.8140
Epoch 162/200
8/8 [==============================] - 0s 2ms/step - loss: 0.3807 - accuracy: 0.8471
Epoch 163/200
8/8 [==============================] - 0s 3ms/step - loss: 0.3781 - accuracy: 0.8678
Epoch 164/200
8/8 [==============================] - 0s 2ms/step - loss: 0.4021 - accuracy: 0.7934
Epoch 165/200

8/8 [==============================] - 0s 5ms/step - loss: 0.3818 - accuracy: 0.8430
Epoch 166/200
8/8 [==============================] - 0s 3ms/step - loss: 0.3726 - accuracy: 0.8595
Epoch 167/200
8/8 [==============================] - 0s 1ms/step - loss: 0.3825 - accuracy: 0.8347
Epoch 168/200
8/8 [==============================] - 0s 2ms/step - loss: 0.3759 - accuracy: 0.8430
Epoch 169/200
8/8 [==============================] - 0s 1ms/step - loss: 0.3975 - accuracy: 0.8264
Epoch 170/200
8/8 [==============================] - 0s 1ms/step - loss: 0.4137 - accuracy: 0.8058
Epoch 171/200
8/8 [==============================] - 0s 2ms/step - loss: 0.3695 - accuracy: 0.8512
Epoch 172/200
8/8 [==============================] - 0s 1ms/step - loss: 0.3720 - accuracy: 0.8347
Epoch 173/200
8/8 [==============================] - 0s 1ms/step - loss: 0.3737 - accuracy: 0.8471
Epoch 174/200
8/8 [==============================] - 0s 3ms/step - loss: 0.3695 - accuracy: 0.8471
Epoch 175/200
8/8 [==============================] - 0s 1ms/step - loss: 0.3716 - accuracy: 0.8471
Epoch 176/200
8/8 [==============================] - 0s 1ms/step - loss: 0.3701 - accuracy: 0.8388
Epoch 177/200
8/8 [==============================] - 0s 1ms/step - loss: 0.3720 - accuracy: 0.8554
Epoch 178/200
8/8 [==============================] - 0s 1ms/step - loss: 0.3762 - accuracy: 0.8471
Epoch 179/200
8/8 [==============================] - 0s 1ms/step - loss: 0.3698 - accuracy: 0.8512
Epoch 180/200
8/8 [==============================] - 0s 2ms/step - loss: 0.3650 - accuracy: 0.8471
Epoch 181/200
8/8 [==============================] - 0s 2ms/step - loss: 0.3738 - accuracy: 0.8512
Epoch 182/200
8/8 [==============================] - 0s 2ms/step - loss: 0.3693 - accuracy: 0.8636
Epoch 183/200
8/8 [==============================] - 0s 2ms/step - loss: 0.3705 - accuracy: 0.8430
Epoch 184/200
8/8 [==============================] - 0s 1ms/step - loss: 0.3906 - accuracy: 0.8182
Epoch 185/200
8/8 [==============================] - 0s 5ms/step - loss: 0.4254 - accuracy: 0.8017
Epoch 186/200
8/8 [==============================] - 0s 1ms/step - loss: 0.5047 - accuracy: 0.7810
Epoch 187/200
8/8 [==============================] - ETA: 0s - loss: 0.4926 - accuracy: 0.75 - 0s 1ms/step - loss: 0.3858 - accuracy: 0.8182
Epoch 188/200
8/8 [==============================] - 0s 1ms/step - loss: 0.3812 - accuracy: 0.8430
Epoch 189/200
8/8 [==============================] - 0s 1ms/step - loss: 0.3699 - accuracy: 0.8512
Epoch 190/200
8/8 [==============================] - 0s 3ms/step - loss: 0.3727 - accuracy: 0.8595
Epoch 191/200
8/8 [==============================] - 0s 1ms/step - loss: 0.3965 - accuracy: 0.8140
Epoch 192/200
8/8 [==============================] - 0s 2ms/step - loss: 0.3897 - accuracy: 0.8388
Epoch 193/200
8/8 [==============================] - 0s 2ms/step - loss: 0.3710 - accuracy: 0.8595
Epoch 194/200
8/8 [==============================] - 0s 2ms/step - loss: 0.3909 - accuracy: 0.8223
Epoch 195/200
8/8 [==============================] - 0s 2ms/step - loss: 0.4111 - accuracy: 0.8223
Epoch 196/200
8/8 [==============================] - 0s 2ms/step - loss: 0.3807 - accuracy: 0.8388
Epoch 197/200
8/8 [==============================] - 0s 1ms/step - loss: 0.3824 - accuracy: 0.8471
Epoch 198/200
8/8 [==============================] - 0s 4ms/step - loss: 0.3815 - accuracy: 0.8347
Epoch 199/200
8/8 [==============================] - 0s 2ms/step - loss: 0.3700 - accuracy: 0.8306
Epoch 200/200
8/8 [==============================] - 0s 1ms/step - loss: 0.3630 - accuracy: 0.8512

In [48]:
model.save('heart_pred1.h5')

In [49]:
model.predict([[45,1,3,110,264,0,1,132,0,1.2,1,0,3],[63,1,3,145,233,1,0,150,0,2.3,0,0,1]])

array([[0.6168583],
       [0.6554928]], dtype=float32)

In [50]:
model.get_weights()

[array([[-0.3472098 ,  0.14504766,  0.4207894 ,  0.38274935, -0.10022948,
          0.47362912, -0.1727623 ,  0.21529524,  0.24178995,  0.02192121,
          0.06093594, -0.16055785],
        [-0.3071824 ,  0.04248445,  0.04607931, -0.11322538,  0.4211852 ,
         -0.04636807, -0.3948788 , -0.2073484 ,  0.40010205, -0.16825762,
          1.0624528 , -0.65055823],
        [-0.03308523,  0.01183836,  0.09142801,  0.32629707, -0.27578864,
          0.49163064,  0.20662956,  0.5106757 , -0.53793365,  0.41622886,
         -0.8935932 ,  0.29857767],
        [-0.34353828,  0.44643065,  0.14998856, -0.01823843,  0.16181388,
          0.26209968, -0.06716211, -0.4064399 ,  0.30522087, -0.33311364,
         -0.47153765, -0.06656881],
        [ 0.01303592,  0.10928871, -0.24112467,  0.38210094,  0.26665154,
          0.02199594,  0.00580229,  0.13930447,  0.00886487,  0.44302604,
          0.31627125,  0.14969824],
        [-0.14338392, -0.28610533, -0.36587128,  0.4146908 ,  0.38324752,
          0.15625699,  0.39827856,  0.09980937,  0.3093143 , -0.547081  ,
         -0.3391412 , -0.12332321],
        [ 0.01822475, -0.3873136 ,  0.15991381, -0.21314813, -0.60450125,
          0.44630364,  0.3064182 ,  0.37935784,  0.16878077,  0.29470778,
          0.19953671,  0.113272  ],
        [-0.19098163, -0.03263815, -0.4640749 , -0.06793451,  0.05563546,
         -0.43351996,  0.24879858, -0.09436007, -0.36176613, -0.23846084,
          0.14126803,  0.21646234],
        [ 0.4211364 ,  0.20723207,  0.11215231, -0.8985917 ,  0.09324221,
         -0.5338649 , -0.8252812 ,  0.01557537,  1.1250821 , -0.07906312,
          0.9175132 , -0.32757413],
        [-0.10723898,  0.65810275,  0.1691719 , -0.81080025,  0.2203289 ,
         -0.71086365, -0.21222654, -0.30986425,  0.17060323, -0.44477683,
          0.43319318, -0.34039223],
        [ 0.46846333,  0.32650822,  0.19560215,  0.41266054,  0.16293806,
          0.6756975 ,  0.08920662, -0.15875041, -0.6545705 ,  0.12603578,
         -0.5671481 , -0.22323267],
        [-0.07818422,  0.6224442 ,  0.37197015, -0.09220469,  0.32823804,
         -0.08990186, -0.8848251 ,  0.25952548,  0.8130314 , -0.76463705,
          0.31471774, -0.22518732],
        [ 0.43956336, -0.26047948,  0.2548497 , -0.16745612,  0.04267423,
         -0.2826676 , -0.58491826, -0.07957806,  0.6601994 ,  0.08341353,
          0.6612763 , -0.39884773]], dtype=float32),
 array([ 0.        ,  0.02606465,  0.        , -0.03325673,  0.02735871,
         0.00520691, -0.01418885, -0.05371077, -0.04348826, -0.02305282,
        -0.00016922, -0.03172867], dtype=float32),
 array([[-5.1933527e-04,  2.8619069e-01, -3.6982435e-01, -4.5823741e-01,
         -3.1990623e-01, -4.3107304e-01,  2.1758932e-01, -2.9804397e-01],
        [ 1.2371335e-01,  3.8322067e-01, -1.6606398e-01, -1.0542935e-01,
         -4.2532578e-01, -3.0231705e-01,  8.4717095e-02,  4.1312125e-01],
        [ 4.1469687e-01, -4.1907406e-01,  3.7658435e-01, -2.6509574e-01,
         -1.3238099e-01,  8.5295022e-02, -3.6386359e-01, -3.2485625e-01],
        [-6.1023675e-02,  2.8905243e-02,  3.6650434e-01, -4.4220835e-01,
          2.5625134e-01, -1.1909025e-01,  8.7705955e-02, -2.5654507e-01],
        [-3.6279875e-01,  5.3257424e-01,  3.6809910e-02,  2.3971444e-01,
         -1.5003085e-03, -8.4989555e-02,  5.9470195e-02,  1.3331935e-01],
        [-2.5087163e-01, -1.4794146e-01,  5.7961845e-01, -4.7125605e-01,
          1.4293259e-01,  4.8131144e-01, -2.9589260e-01, -1.3290009e-01],
        [-4.1561842e-01, -2.5837019e-01,  8.3561073e-04, -3.5696650e-01,
         -1.3098657e-02, -1.0478054e-01,  2.5303119e-01,  1.1995316e-01],
        [-2.9418263e-01, -2.6926784e-02,  2.2362014e-02,  4.1221899e-01,
         -1.9461587e-01, -3.0110177e-01,  2.3151805e-01, -1.3118166e-01],
        [ 2.0038333e-02,  2.3182647e-01,  4.7651686e-02, -9.2502654e-02,
         -2.8259131e-01,  3.7881663e-01, -8.5009031e-02, -2.5647390e-01],
        [-4.2523280e-01,  4.6779555e-01,  4.4047689e-01, -1.8576583e-01,
         -5.4501784e-01, -3.8774580e-02,  1.5081720e-01, -4.4832550e-02],
        [ 3.1969973e-01, -2.3332281e-01, -1.5817621e-01,  3.9207238e-01,
         -5.4561710e-01,  1.7475410e-01, -3.1413352e-01, -2.1105695e-01],
        [ 3.6075899e-01,  5.3351276e-02, -1.1832641e-01, -5.3603059e-01,
         -5.2630782e-01,  2.6654804e-01,  3.4214836e-01,  1.0753560e-01]],
       dtype=float32),
 array([-0.01342711,  0.02633669, -0.02699968,  0.        ,  0.        ,
        -0.01616379, -0.02707934,  0.03170914], dtype=float32),
 array([[-0.709552  ],
        [-0.5409182 ],
        [ 0.705784  ],
        [ 0.13496017],
        [-0.531792  ],
        [ 0.4885629 ],
        [ 0.5111333 ],
        [ 0.52090675]], dtype=float32),
 array([-0.02677918], dtype=float32)]

In [43]:
dataset

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [91]:
dataset.iloc[0:3]

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1

In [52]:
from tensorflow import keras
model = keras.models.load_model('heart_pred1.h5')

In [53]:
y_pred=model.predict(x_test)

In [54]:
y_pred

array([[6.65582716e-02],
       [6.73565865e-01],
       [9.89008486e-01],
       [1.15716159e-02],
       [9.25807416e-01],
       [9.57351923e-01],
       [4.02479291e-01],
       [4.81724739e-04],
       [3.65763903e-03],
       [4.98634338e-01],
       [5.62593341e-01],
       [5.09951413e-02],
       [7.86108851e-01],
       [1.66417360e-02],
       [9.31865811e-01],
       [9.08826113e-01],
       [9.54545677e-01],
       [6.11037314e-02],
       [3.72391939e-03],
       [9.66638327e-03],
       [6.42709315e-01],
       [1.71212852e-02],
       [4.93341833e-01],
       [5.59746981e-01],
       [7.98388839e-01],
       [7.72917211e-01],
       [8.73713195e-01],
       [6.32406116e-01],
       [8.22177529e-03],
       [7.85351038e-01],
       [5.41908741e-02],
       [2.13249326e-02],
       [7.90479779e-03],
       [1.64815277e-01],
       [5.77609837e-01],
       [7.56274164e-02],
       [6.51781797e-01],
       [7.75665224e-01],
       [7.88317204e-01],
       [8.19830239e-01],
       [4.15179491e-01],
       [5.81023097e-01],
       [7.92003989e-01],
       [7.36300945e-01],
       [8.03570867e-01],
       [5.10612130e-03],
       [6.13319755e-01],
       [9.05856848e-01],
       [1.45454705e-02],
       [1.67638659e-02],
       [6.40144348e-02],
       [5.28773665e-03],
       [6.49002254e-01],
       [8.31366718e-01],
       [2.72060812e-01],
       [2.68942118e-03],
       [4.50862944e-02],
       [8.86402190e-01],
       [1.11320615e-02],
       [2.68533826e-03],
       [2.85082757e-02]], dtype=float32)

In [55]:
y_test

179    0
228    0
111    1
246    0
60     1
      ..
249    0
104    1
300    0
193    0
184    0
Name: output, Length: 61, dtype: int64

In [56]:
model.evaluate(x_train,y_train)

8/8 [==============================] - 0s 1ms/step - loss: 0.3707 - accuracy: 0.8636

[0.3706745505332947, 0.8636363744735718]

In [57]:
from sklearn import metrics

In [58]:
print(metrics.accuracy_score(y_test,y_pred.round()))

0.8360655737704918

In [63]:
print(metrics.confusion_matrix(y_test,y_pred.round()))

[[25  4]
 [ 6 26]]

In [54]:
# Using Logistic Regression() Also

In [67]:
import pandas as pd

In [68]:
dataset=pd.read_csv('heart.csv')

In [69]:
dataset

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [70]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trtbps    303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalachh  303 non-null    int64
 8   exng      303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slp       303 non-null    int64
 11  caa       303 non-null    int64
 12  thall     303 non-null    int64
 13  output    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [71]:
y=dataset['output']

In [72]:
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: output, Length: 303, dtype: int64

In [73]:
dataset.columns

Index(['age', 'sex', 'cp', 'trtbps', 'chol', 'fbs', 'restecg', 'thalachh',
       'exng', 'oldpeak', 'slp', 'caa', 'thall', 'output'],
      dtype='object')

In [74]:
x=dataset[['age', 'sex', 'cp', 'trtbps', 'chol', 'fbs', 'restecg', 'thalachh',
       'exng', 'oldpeak', 'slp', 'caa', 'thall']]

In [75]:
x

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2

In [76]:
dataset.corr()

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
age,1.000000,-0.098447,-0.068653,0.279351,0.213678,0.121308,-0.116211,-0.398522,0.096801,0.210013,-0.168814,0.276326,0.068001,-0.225439
sex,-0.098447,1.000000,-0.049353,-0.056769,-0.197912,0.045032,-0.058196,-0.044020,0.141664,0.096093,-0.030711,0.118261,0.210041,-0.280937
cp,-0.068653,-0.049353,1.000000,0.047608,-0.076904,0.094444,0.044421,0.295762,-0.394280,-0.149230,0.119717,-0.181053,-0.161736,0.433798
trtbps,0.279351,-0.056769,0.047608,1.000000,0.123174,0.177531,-0.114103,-0.046698,0.067616,0.193216,-0.121475,0.101389,0.062210,-0.144931
chol,0.213678,-0.197912,-0.076904,0.123174,1.000000,0.013294,-0.151040,-0.009940,0.067023,0.053952,-0.004038,0.070511,0.098803,-0.085239
fbs,0.121308,0.045032,0.094444,0.177531,0.013294,1.000000,-0.084189,-0.008567,0.025665,0.005747,-0.059894,0.137979,-0.032019,-0.028046
restecg,-0.116211,-0.058196,0.044421,-0.114103,-0.151040,-0.084189,1.000000,0.044123,-0.070733,-0.058770,0.093045,-0.072042,-0.011981,0.137230
thalachh,-0.398522,-0.044020,0.295762,-0.046698,-0.009940,-0.008567,0.044123,1.000000,-0.378812,-0.344187,0.386784,-0.213177,-0.096439,0.421741
exng,0.096801,0.141664,-0.394280,0.067616,0.067023,0.025665,-0.070733,-0.378812,1.000000,0.288223,-0.257748,0.115739,0.206754,-0.436757
oldpeak,0.210013,0.096093,-0.149230,0.193216,0.053952,0.005747,-0.058770,-0.344187,0.288223,1.000000,-0.577537,0.222682,0.210244,-0.430696
slp,-0.168814,-0.030711,0.119717,-0.121475,-0.004038,-0.059894,0.093045,0.386784,-0.257748,-0.577537,1.000000,-0.080155,-0.104764,0.345877
caa,0.276326,0.118261,-0.181053,0.101389,0.070511,0.137979,-0.072042,-0.213177,0.115739,0.222682,-0.080155,1.000000,0.151832,-0.391724
thall,0.068001,0.210041,-0.161736,0.062210,0.098803,-0.032019,-0.011981,-0.096439,0.206754,0.210244,-0.104764,0.151832,1.000000,-0.344029
output,-0.225439,-0.280937,0.433798,-0.144931,-0.085239,-0.028046,0.137230,0.421741,-0.436757,-0.430696,0.345877,-0.391724,-0.344029,1.000000

In [77]:
type(y)

pandas.core.series.Series

In [78]:
y.values

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [79]:
x.shape

(303, 13)

In [80]:

from sklearn.model_selection import train_test_split

In [81]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

In [82]:

from sklearn.linear_model import LogisticRegression

In [83]:
model=LogisticRegression()

In [84]:
model.fit(x_train,y_train)

C:\Users\Dell\Upmanyu\anaconda3\envs\arthnew\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

LogisticRegression()

In [85]:
model.coef_

array([[ 0.01409301, -1.11713301,  0.78204326, -0.01144372, -0.00203277,
         0.00138337,  0.48266918,  0.02581627, -0.77915027, -0.69536303,
         0.58280331, -0.75474482, -0.9692382 ]])

In [93]:
y_predict=model.predict(x_test)
y_predict

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [94]:
y_test

179    0
228    0
111    1
246    0
60     1
      ..
249    0
104    1
300    0
193    0
184    0
Name: output, Length: 61, dtype: int64

In [95]:
from sklearn.metrics import accuracy_score

In [96]:
score=accuracy_score(y_test,y_predict)

In [97]:
score

0.8852459016393442

In [99]:
score

0.8852459016393442

In [101]:
import joblib

In [102]:
joblib.dump(model,'heart_predict(88%).pk1')

['heart_predict(88%).pk1']

In [103]:
model=joblib.load('heart_predict(85).pk1')

In [100]:
y_predict=model.predict(x_train)